
include:
  - local: 'templates/rules.yml'
  
stages:
- postChaos

image: <image_with_ansible>

postChaosTets:
  
    extends: .rule_policy
    #needs: 
     # - job: chaosTesting
      #  artifacts: true
        
    stage: postChaos
    only: 
    - pipeline
  
    script: |

      ANSIBLE_BECOME_PASS="${ANSIBLE_PASS}"
          ansible-playbook -i inventory.ini -u $SSH_USER playbook.yml -e "gitlab_pipeline_id=$GITLAB_PIPELINE_ID pipeline_name=$PIPELINE_NAME job_status=$CI_JOB_STATUS job_name=$JOB_NAME cluster=$CLUSTER ci_user=$CI_USER"

    artifacts:
      paths:
      - public
      expire_in: 1 hour
      
    tags:
        - graas-like
        - nis
        - k8s


