# delete_pods.yml
- name: Find namespace for current filter
  shell: >
    kubectl get pods --all-namespaces --no-headers |
    grep {{ current_filter }} | awk '{print $1}' | head -n 1
  register: namespace_result
  changed_when: false
  failed_when: namespace_result.stdout == ""


- name: Définir le numéro basé sur current_filter
  set_fact:
    namespace: "{{ namespace_result.stdout | trim }}"
    resi_test_number: >-
      {% if current_filter == 'sm-pgw-session' %}
        23
      {% elif current_filter == 'pfcp' %}
        27
      {% elif current_filter == 'sm-udp-forwarder' %}
        36
      {% elif current_filter == 'mm-mobility' %}
        31
      {% elif current_filter == 'up-data-plane' %}
        24
      {% elif current_filter == 'sm-ip-allocator' %}
        37
      {% elif current_filter == 'sm-controller' %}
        41
      {% elif current_filter == 'kvdb' %}
        42
      {% elif current_filter == 'sm-sgw-session' %}
        33
      {% elif current_filter == 'mm-controller' %}
        26
      {% elif current_filter == 'mm-sctp' %}
        30
      {% elif current_filter == 'mm-forwarder' %}
        32
      {% else %}
        00
      {% endif %}

- name: set dynamically the the resilience number
  set_fact:
    remote_artifact_path: "/tmp/RESI-TEST-{{resi_test_number | trim}}-{{current_filter}}.md"


- name: Capture pod state before deletion
  shell: |
    echo "# Pod's state before deletion for filter: {{ current_filter }}" >> {{ remote_artifact_path }}
    echo "" >> {{ remote_artifact_path }}
    echo '```' >> {{ remote_artifact_path }}
    kubectl get pods -n {{ namespace }} -o wide | grep {{ current_filter }} >> {{ remote_artifact_path }}
    echo '```' >> {{ remote_artifact_path }}

- name: List matching pods
  shell: "kubectl get pod -n {{ namespace }} | grep {{ current_filter }} | awk '{print $1}'"
  register: pod_list
  changed_when: false

- name: Fail if no pod found
  fail:
    msg: "No pod found matching '{{ current_filter }}' in namespace '{{ namespace }}'."
  when: pod_list.stdout == ""

- name: Choose random pod to delete
  set_fact:
    pod_name: "{{ pod_list.stdout.split() | random }}"

- name: Log pod about to be deleted
  shell: |
    echo "# Deleting POD matching {{ current_filter }}" >> {{ remote_artifact_path }}
    echo "" >> {{ remote_artifact_path }}
    echo "Pod deleted : {{ pod_name }}" >> {{ remote_artifact_path }}

- name: Delete the pod
  shell: "kubectl delete pod {{ pod_name }} -n {{ namespace }}"
  register: delete_result

- name: Log post-deletion state
  shell: |
    echo "# State after deletion" >> {{ remote_artifact_path }}
    echo "" >> {{ remote_artifact_path }}
    echo '```' >> {{ remote_artifact_path }}
    kubectl get pods -n {{ namespace }} -o wide | grep {{ current_filter }} >> {{ remote_artifact_path }}
    echo '```' >> {{ remote_artifact_path }}

- name: Check if new pod is created
  shell: |
    kubectl get pods -n {{ namespace }} --sort-by=.metadata.creationTimestamp \
      | grep {{ current_filter }} | tail -n 1 | awk '{print $1}'
  register: latest_pod_name
  changed_when: false

- name: Check pod status
  shell: |
    kubectl get pod -n {{ namespace }} {{ latest_pod_name.stdout }} -o jsonpath='{.status.phase}'
  register: latest_pod_status
  changed_when: false

- name: Log for new pod info
  shell: |
    echo "# New pod status" >> {{ remote_artifact_path }}
    echo "" >> {{ remote_artifact_path }}
    echo "Pod name: {{ latest_pod_name.stdout }}" >> {{ remote_artifact_path }}
    echo "" >> {{ remote_artifact_path }}
    echo "Pod Status: {{ latest_pod_status.stdout }}" >> {{ remote_artifact_path }}
  when: latest_pod_name.stdout != ""


# Set the Right AMF 
- name: Define the right AMF ip address
  set_fact:
    amf_ip_address: >-
      {% if cluster == 'eccd6' %}
        172.19.20.81
      {% elif cluster == 'eccd5' %}
        172.19.20.73
      {% else %}
        00
      {% endif %}

# Connection to amf 
- name: SSH connection to AMF and Get CPU Load
  command: ssh -o StrictHostKeyChecking=no pcc-admin@"{{amf_ip_address | trim}}" gsh get_eq_cpu_load 
  register: node_hostname
  changed_when: false
  failed_when: node_hostname.rc != 0
  delegate_to: localhost
  when: current_filter == "mm-controller"


# copy data from amf
- name: Copy data from amf to remote artifact file
  shell: |
    echo "# CPU LOAD FROM AMF " >> {{ remote_artifact_path }}
    echo "{{ node_hostname.stdout }}" >> {{ remote_artifact_path }}
  when: current_filter == "mm-controller"


# Connection to amf and retrieve alarms
- name: SSH connection to AMF and Get alarms
  command: ssh -o StrictHostKeyChecking=no pcc-admin@"{{amf_ip_address | trim}}" gsh list_alarms
  register: alarms
  changed_when: false
  failed_when: node_hostname.rc != 0
  delegate_to: localhost
  when: current_filter == "mm-sctp"

# copy data from amf
- name: Copy alarms from amf to remote artifact file
  shell: |
    echo "# ALARMS FROM AMF " >> {{ remote_artifact_path }}
    echo '```' >> {{ remote_artifact_path }}
    echo "{{ alarms.stdout }}" >> {{ remote_artifact_path }}
    echo '```' >> {{ remote_artifact_path }}
  when: current_filter == "mm-sctp"

# this task is executed to get logs from kvdb operator
- name: List matching pods for kvdb operator
  shell: "kubectl get pod -n {{ namespace }} | grep kvdb-rd-operator | awk '{print $2}'"
  register: pod_list_kvdb_operator
  changed_when: false
  when: current_filter == "kvdb"

# Get log from kvdb operator
- name: Get logs from kvdb operator
  shell: kubectl logs {{ pod_list_kvdb_operator.stdout }} -n {{ namespace }} | tail -n 10
  register: kvdb_operator_logs
  changed_when: false
  when: current_filter == "kvdb"

# Copy data from kvdb operator to remote artifact file
- name: Copy logs from kvdb to remote artifact file
  shell: |
    echo "# Logs From Kvdb Operator " >> {{ remote_artifact_path }}
    echo '```' >> {{ remote_artifact_path }}
    echo "{{ kvdb_operator_logs.stdout }}" >> {{ remote_artifact_path }}
    echo '```' >> {{ remote_artifact_path }}
  when: current_filter == "kvdb"






