    - name: Restart un master node when the action is 'reboot_master'
      block:
        - name: Get the Ip adress of master
          command: kubectl get nodes --selector='node-role.kubernetes.io/control-plane' -o jsonpath='{.items[*].status.addresses[?(@.type=="InternalIP")].address}'
          register: k8s_masters_ips

        - name: Select an IP adress of one of the master
          set_fact:
            random_master_ip: "{{ k8s_masters_ips.stdout.split() | random }}"

        - name: SSH connection to the random node and get the hostname
          command: ssh -o StrictHostKeyChecking=no {{ random_master_ip }} hostname -s
          register: node_hostname
          changed_when: false
          failed_when: node_hostname.rc != 0

        - name: Set hostname fact
          set_fact:
            master_hostname: "{{ node_hostname.stdout | trim }}" 

        - name: Print the  hostname of the rebooted node
          debug:
            msg: "The rebooted master is: {{ master_hostname }}"

        - name: Reboot the master
          command: ssh {{ random_master_ip }} sudo reboot
          async: 1
          poll: 0
      when: action == "reboot_master"